# Generated by Django 4.2.1 on 2023-05-25 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_rename_author_id_todo_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="author",
        ),
    ]
